<?php

/**
 * @file
 * Contains demo_plugin_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function demo_plugin_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the demo_plugin_api module.
    case 'help.page.demo_plugin_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extensible demo by Plugin API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function demo_plugin_api_theme() {
  return [
    'demo_plugin_api' => [
      'render element' => 'children',
    ],
  ];
}
